console.log(10 * 3)
console.log(314 % 100)
console.log(Infinity - 1)
console.log(Infinity - Infinity)
console.log("This is the first line\nAnd this is the second")
console.log(typeof 4.5)
console.log(3>2)
console.log(3<2)
console.log((1 + 1) == 2 && (10 * 10) > 50)
